export enum DropDownListEnum {
    LOAI_KHACH_HANG,
    NGUON_KHACH_HANG,
    NHAN_VIEN_PHU_TRACH,
    TRANG_THAI_KHACH_HANG,
    LOAI_CHAM_SOC,
    TRANG_THAI_CHAM_SOC,

    LOAI_DE_THI,
    TRANG_THAI_DE_THI,
    LOAI_LOP_HOC,
    TRANG_THAI_LOP_HOC,

    TRANG_THAI_HOC_VIEN,
    LOAI_HOC_VIEN,

    LOAI_DAT_LICH,
    TRANG_THAI_DAT_LICH,
    LOAI_NHAN_VIEN,
    TRANG_THAI_NHAN_VIEN,
    LOAD_ROLE,
    LOAD_DAN_TOC,
    LOAD_TON_GIAO,

    LOAI_DICH_VU,
    TRANG_THAI_DICH_VU,

    LOAI_BO_SAN_PHAM,
    TRANG_THAI_BO_SAN_PHAM,

    LOAI_SAN_PHAM,
    TRANG_THAI_SAN_PHAM,

    LOAI_DON_HANG,
    TRANG_THAI_DON_HANG,

    DICH_VU_ID,
    BO_SAN_PHAM_ID
}